// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vn4GCfRoYe35APzZGsNDnF
import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { CommerceProviderComponent } from "@plasmicpkgs/commerce-bigcommerce"; // plasmic-import: JuJYgKZmrTfxxT/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  commerceProviderComponentProps?: Partial<
    Omit<React.ComponentProps<typeof CommerceProviderComponent>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, commerceProviderComponentProps } = props;

  return (
    <CommerceProviderComponent
      {...commerceProviderComponentProps}
      accessToken={
        commerceProviderComponentProps &&
        "accessToken" in commerceProviderComponentProps
          ? commerceProviderComponentProps.accessToken!
          : ("zyty8y66wgnjhov3xko5neimm9waqu" as const)
      }
      channelId={
        commerceProviderComponentProps &&
        "channelId" in commerceProviderComponentProps
          ? commerceProviderComponentProps.channelId!
          : undefined
      }
      clientId={
        commerceProviderComponentProps &&
        "clientId" in commerceProviderComponentProps
          ? commerceProviderComponentProps.clientId!
          : ("ey4rzqfy84m696cprvxhnomaarvg0nm" as const)
      }
      clientName={
        commerceProviderComponentProps &&
        "clientName" in commerceProviderComponentProps
          ? commerceProviderComponentProps.clientName!
          : ("David" as const)
      }
      clientSecret={
        commerceProviderComponentProps &&
        "clientSecret" in commerceProviderComponentProps
          ? commerceProviderComponentProps.clientSecret!
          : ("9bc59dd1a232bce7d4be8db37ff91d2093bf6b8dcde7d91e4f69391284ed7fc7" as const)
      }
      storeFrontApiToken={
        commerceProviderComponentProps &&
        "storeFrontApiToken" in commerceProviderComponentProps
          ? commerceProviderComponentProps.storeFrontApiToken!
          : ("eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJjaWQiOjEsImNvcnMiOlsiaHR0cHM6Ly9kZXZlbG9wZXIuYmlnY29tbWVyY2UuY29tIl0sImVhdCI6MTY3NzY3MjU0MCwiaWF0IjoxNjc3NDk5NzQwLCJpc3MiOiJCQyIsInNpZCI6MTAwMjg1OTgxNSwic3ViIjoiYmNhcHAubGlua2VyZCIsInN1Yl90eXBlIjowLCJ0b2tlbl90eXBlIjoxfQ.vxQpvMzAftRHdF4lG1U0WlDjqjpISvcRvgWNeeAKX3aZb63RhTM6t4f-r2xykt1KHbnNjBC4NiZPUwqH8Nd0_Q" as const)
      }
      storeHash={
        commerceProviderComponentProps &&
        "storeHash" in commerceProviderComponentProps
          ? commerceProviderComponentProps.storeHash!
          : ("y9qp9pxpug" as const)
      }
    >
      {children}
    </CommerceProviderComponent>
  );
}
